---Q1
ALTER TABLE sales_dataset_rfm_prj
ALTER COLUMN priceeach TYPE NUMERIC USING priceeach::NUMERIC,
ALTER COLUMN ordernumber TYPE NUMERIC USING ordernumber::NUMERIC,
ALTER COLUMN quantityordered TYPE NUMERIC USING quantityordered::NUMERIC,
ALTER COLUMN orderlinenumber TYPE NUMERIC USING orderlinenumber::NUMERIC,
ALTER COLUMN sales TYPE NUMERIC USING sales::NUMERIC,
ALTER COLUMN orderdate TYPE DATE USING orderdate::DATE

---Q2
SELECT *
FROM sales_dataset_rfm_prj
WHERE 
  ORDERNUMBER IS NULL OR
  QUANTITYORDERED IS NULL OR
  PRICEEACH IS NULL OR
  ORDERLINENUMBER IS NULL OR
  SALES IS NULL OR
  ORDERDATE IS NULL

---Q3
ALTER TABLE sales_dataset_rfm_prj
ADD COLUMN CONTACTLASTNAME VARCHAR(255),
ADD COLUMN CONTACTFIRSTNAME VARCHAR(255)
UPDATE sales_dataset_rfm_prj
SET
  CONTACTLASTNAME = INITCAP(TRIM(SPLIT_PART(CONTACTFULLNAME, '-', 1))),
  CONTACTFIRSTNAME = INITCAP(TRIM(SPLIT_PART(CONTACTFULLNAME, '-', 2))

---Q4
ALTER TABLE sales_dataset_rfm_prj
ADD COLUMN QTR_ID INTEGER,
ADD COLUMN MONTH_ID INTEGER,
ADD COLUMN YEAR_ID INTEGER
UPDATE sales_dataset_rfm_prj
SET
  QTR_ID = EXTRACT(QUARTER FROM ORDERDATE),
  MONTH_ID = EXTRACT(MONTH FROM ORDERDATE),
  YEAR_ID = EXTRACT(YEAR FROM ORDERDATE)

---Q5
  WITH stats AS (
  SELECT
    AVG(QUANTITYORDERED) AS avg_quantity,
    STDDEV(QUANTITYORDERED) AS stddev_quantity
  FROM sales_dataset_rfm_prj
)
SELECT *
FROM sales_dataset_rfm_prj
JOIN stats ON true
WHERE ABS((QUANTITYORDERED - avg_quantity) / stddev_quantity) > 3

UPDATE sales_dataset_rfm_prj
SET QUANTITYORDERED = AVG(QUANTITYORDERED)
WHERE ABS((QUANTITYORDERED - AVG(QUANTITYORDERED)) / STDDEV(QUANTITYORDERED)) > 3

DELETE FROM sales_dataset_rfm_prj
WHERE ABS((QUANTITYORDERED - AVG(QUANTITYORDERED)) / STDDEV(QUANTITYORDERED)) > 3

---Q6
CREATE TABLE SALES_DATASET_RFM_PRJ_CLEAN AS
SELECT * FROM sales_dataset_rfm_prj



